In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from load import load_data
import numpy as np

In [2]:


AAPL_data =load_data(r'C:\Users\ASUS VIVO\Desktop\data\AMZN_historical_data.csv')

In [3]:
AAPL_data.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
0,1997-05-15,0.121875,0.125000,0.096354,0.097917,0.097917,1443120000,0.0,0.0
1,1997-05-16,0.098438,0.098958,0.085417,0.086458,0.086458,294000000,0.0,0.0
2,1997-05-19,0.088021,0.088542,0.081250,0.085417,0.085417,122136000,0.0,0.0
3,1997-05-20,0.086458,0.087500,0.081771,0.081771,0.081771,109344000,0.0,0.0
4,1997-05-21,0.081771,0.082292,0.068750,0.071354,0.071354,377064000,0.0,0.0

In [4]:
AAPL_data=AAPL_data.drop(['Date','Dividends','Stock Splits'],axis=1)

In [5]:
AAPL_data.columns = ['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']

AAPL_data.columns

Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [6]:
df=load_data(r'C:\Users\ASUS VIVO\Desktop\data\raw_analyst_ratings.csv').drop('Unnamed: 0',axis=1)

In [7]:
dates = AAPL_data.index
text_data = pd.DataFrame(dates, columns=['Date'])

In [8]:
headline_samples=df['headline']

In [9]:
text_data['Headline'] = np.random.choice(headline_samples, size=len(text_data))

# Display the first few rows of the updated DataFrame
text_data.head()

   Date                                           Headline
0     0  Winthrop Realty Trust Acquires $140.3M Mortgag...
1     1       TD Ameritrade's IMX Index Rose 6% In October
2     2  MITICURE for house Dust Mite Allergic Rhinitis...
3     3  BTIG Sets $12 Price Target On Rockwell Medical...
4     4  Glaxo, Theravance Confirms FDA Panel Has Recom...

In [10]:
text_data.head(30)

    Date                                           Headline
0      0  Winthrop Realty Trust Acquires $140.3M Mortgag...
1      1       TD Ameritrade's IMX Index Rose 6% In October
2      2  MITICURE for house Dust Mite Allergic Rhinitis...
3      3  BTIG Sets $12 Price Target On Rockwell Medical...
4      4  Glaxo, Theravance Confirms FDA Panel Has Recom...
5      5                       Stocks Hitting 52-Week Highs
6      6  'Can't make this sh-t up: the pending doj anno...
7      7  Algeria's Sonatrach in Talks With Exxon Mobil,...
8      8  Energy Drinks Linked with Higher Heart Contrac...
9      9  Albemarle Announces 14% Increase in Quarterly ...
10    10  #PreMarket Primer: Tuesday, November 5: Fed Sp...
11    11  Jefferies Downgrades IPC Healthcare to Hold, R...
12    12  How Artificial Intelligence Is Driving The Fin...
13    13  Feltl and Company Reiterates Strong Buy Rating...
14    14  Citigroup Downgrades Qorvo to Neutral, Raises ...
15    15  Shares of several industrial companies are tra...
16    16  Height Securities, On Fiduciary Rule, Says Fin...
17    17  Juniper Pharmaceuticals Reports Regulatory App...
18    18           Stocks That Hit 52-Week Lows On Thursday
19    19  Uralkali Chair Issues Statement: Calls for Imm...
20    20            Open Text Shares Rally On Earnings Beat
21    21  Liberty Star Announces Agreement and Release o...
22    22  Twin Disc, Inc. Declares Regular Quarterly Cas...
23    23  Some Traders Attributing Upside In General Mil...
24    24  Bloomberg Reporting Diamond Offshore Filing Sh...
25    25  Stifel Acquires Sterne Agee For $51.55/share; ...
26    26                    Statoil Posts Drop In Q1 Profit
27    27  Bernstein Initiates Coverage on Centene at Mar...
28    28  Lloyds, Luxottica and Other European Stocks Wo...
29    29  REMINDER: Johnson & Johnson Has PDUFA Date Exp...

In [11]:
from textblob import TextBlob

In [12]:
def calculate_sentiment(text):
    return TextBlob(text).sentiment.polarity

# Applying the sentiment analysis function to your headlines
text_data['Sentiment'] = text_data['Headline'].apply(calculate_sentiment)

In [13]:
combined_data = text_data.set_index('Date').join(AAPL_data['Close'])
combined_data.head()

                                               Headline  Sentiment     Close
Date
0     Winthrop Realty Trust Acquires $140.3M Mortgag...        0.0  0.125000
1          TD Ameritrade's IMX Index Rose 6% In October        0.6  0.098958
2     MITICURE for house Dust Mite Allergic Rhinitis...        0.4  0.088542
3     BTIG Sets $12 Price Target On Rockwell Medical...        0.0  0.087500
4     Glaxo, Theravance Confirms FDA Panel Has Recom...        0.0  0.082292

In [14]:
combined_data['Daily Returns'] = combined_data['Close'].pct_change()

In [15]:
correlation = combined_data['Sentiment'].corr(combined_data['Daily Returns'])
print("Correlation between sentiment and daily stock returns:", correlation)

Correlation between sentiment and daily stock returns: 0.008113215029491376