In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from load import load_data
import numpy as np

In [2]:


AAPL_data =load_data(r'C:\Users\ASUS VIVO\Desktop\data\NVDA_historical_data.csv')

In [3]:
AAPL_data.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
0,1999-01-22,0.043750,0.048828,0.038802,0.041016,0.037621,2714688000,0.0,0.0
1,1999-01-25,0.044271,0.045833,0.041016,0.045313,0.041562,510480000,0.0,0.0
2,1999-01-26,0.045833,0.046745,0.041146,0.041797,0.038337,343200000,0.0,0.0
3,1999-01-27,0.041927,0.042969,0.039583,0.041667,0.038218,244368000,0.0,0.0
4,1999-01-28,0.041667,0.041927,0.041276,0.041536,0.038098,227520000,0.0,0.0

In [4]:
AAPL_data=AAPL_data.drop(['Date','Dividends','Stock Splits'],axis=1)

In [5]:
AAPL_data.columns = ['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']

AAPL_data.columns

Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [6]:
df=load_data(r'C:\Users\ASUS VIVO\Desktop\data\raw_analyst_ratings.csv').drop('Unnamed: 0',axis=1)

In [7]:
dates = AAPL_data.index
text_data = pd.DataFrame(dates, columns=['Date'])

In [8]:
headline_samples=df['headline']

In [9]:
text_data['Headline'] = np.random.choice(headline_samples, size=len(text_data))

# Display the first few rows of the updated DataFrame
text_data.head()

   Date                                           Headline
0     0  Benzinga's Top Upgrades, Downgrades For June 6...
1     1  Benzinga Weekly Preview: Yellen To Take Her Pl...
2     2  The Street Not Taking A Shine To Signet Jewele...
3     3       ETFs to Watch April 19, 2013 (EZA, HDV, XLU)
4     4                        Stocks Hitting 52-Week Lows

In [10]:
text_data.head(30)

    Date                                           Headline
0      0  Benzinga's Top Upgrades, Downgrades For June 6...
1      1  Benzinga Weekly Preview: Yellen To Take Her Pl...
2      2  The Street Not Taking A Shine To Signet Jewele...
3      3       ETFs to Watch April 19, 2013 (EZA, HDV, XLU)
4      4                        Stocks Hitting 52-Week Lows
5      5  NiSource Earlier Reported Q2 EPS $0.05 Misses ...
6      6  Ecopetrol S.A. Reports the Change of Authorize...
7      7  Ferro Raises FY16 Adj. EPS Outlook from $0.93-...
8      8  Baidu's iQIYI.com Subsidiary, Announces Strate...
9      9             18 Biggest Mid-Day Gainers For Tuesday
10    10  Benzinga's Morning Movers (EVVV, NWL, VECO, JSDA)
11    11               NextEra Energy: Q1 Earnings Insights
12    12               Energy Stock Are Leading The Markets
13    13  Stifel Nicolaus Maintains Buy on Belden, Lower...
14    14  Investors Real Estate Trust Reports Q2 AFFO/sh...
15    15  Oppenheimer Sees Solar Names Finding A Base, V...
16    16  Dow Jones Reporting Blackberry Considering BBM...
17    17  Mid-Afternoon Market Update: Dow Drops Over 10...
18    18  Brexit Update: Scottish Court Delays Decision ...
19    19  After-Hours Recap: The Markets' Big Week And S...
20    20                              Morning Market Movers
21    21                         Benzinga's Top Initiations
22    22  JAB Buys Panera; Analyst Foresees Near-Term Sl...
23    23  Drug Retailers Targeting Flu Season - Analyst ...
24    24     The AES Corp Reports Q3 EPS $0.27 vs $0.26 Est
25    25  Benzinga's Commodity Update Gold +0.98%, Natur...
26    26  ARI Network Services Reports Inline Q3 EPS $0....
27    27  EDAP Reports Exclusive Global Distribution Rig...
28    28  Guinea, Sierra Leone Each Recorded Single Case...
29    29  Tax Bill Passes: An Economic Boon? - Analyst Blog

In [11]:
from textblob import TextBlob

In [12]:
def calculate_sentiment(text):
    return TextBlob(text).sentiment.polarity

# Applying the sentiment analysis function to your headlines
text_data['Sentiment'] = text_data['Headline'].apply(calculate_sentiment)

In [13]:
combined_data = text_data.set_index('Date').join(AAPL_data['Close'])
combined_data.head()

                                               Headline  Sentiment     Close
Date
0     Benzinga's Top Upgrades, Downgrades For June 6...   0.500000  0.048828
1     Benzinga Weekly Preview: Yellen To Take Her Pl...   0.136364  0.045833
2     The Street Not Taking A Shine To Signet Jewele...   0.000000  0.046745
3          ETFs to Watch April 19, 2013 (EZA, HDV, XLU)   0.000000  0.042969
4                           Stocks Hitting 52-Week Lows   0.000000  0.041927

In [14]:
combined_data['Daily Returns'] = combined_data['Close'].pct_change()

In [15]:
correlation = combined_data['Sentiment'].corr(combined_data['Daily Returns'])
print("Correlation between sentiment and daily stock returns:", correlation)

Correlation between sentiment and daily stock returns: -0.019824334346640857